[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0


[program:client]
command=node server.js
directory=/app/frontend/.next/standalone
autostart=true
autorestart=true
environment=FASTAPI_URL="http://localhost:8000",PORT="3000"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0


[program:server]
command=uv run uvicorn agent_testing_assignment_rust_rag:app --host 0.0.0.0 --port 8000
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0